/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-04-27 08:18:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.service.MemberService;
import member.model.vo.Member;

public final class enroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1619368507292L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1619184460358L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.service.MemberService");
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String msg = (String) session.getAttribute("msg");
	if (msg != null)
	session.removeAttribute("msg");
	Member loginMember = (Member) session.getAttribute("loginMember");
	//사용자 쿠키처리
	String saveId = null;
	Cookie[] cookies = request.getCookies();
	if (cookies != null) {
		for (Cookie c : cookies) {
			String name = c.getName();
			String value = c.getValue();
			System.out.println(name + " : " + value);
			if ("saveId".equals(name))
		saveId = value;
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<title>미플</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/header.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t<div id=\"background_header_div\">\r\n");
      out.write("\t<div id=\"header_icon\"><img src=\"/semi/images/icon3.png\" id=\"icon4_image\" class=\"icon_image\"></div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"boxContainer\">\r\n");
      out.write("\t\t\t\t<table class=\"elementsContainer\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"searchKeyword\" type=\"text\" placeholder=\"키워드를 입력해주세요\" class=\"search\" onkeyup=\"enterkey();\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"material-icons\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/baseline_search_black_24dp.png\"  onclick=\"search();\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/Logo.png\" id=\"Logo\"/></a>\r\n");
      out.write("\t\t\t<div class=\"login\">\r\n");
      out.write("\t\t\t");

				if (loginMember == null) {
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"로그인\" id=\"login_button\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"회원가입\" id=\"signup_button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/enroll';\">\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<table id=\"login\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"header_td\">");
      out.print(loginMember.getName());
      out.write("님, 안녕하세요.</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"header_td\"><input type=\"button\" value=\"mypage\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/mypage';\" class=\"loginbtn\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"logout\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout';\" class=\"loginbtn\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"loginEnd\"></div>\r\n");
      out.write("\t\t<div id=\"login_frame_wrapper\" >\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<!-- Loginframe 평소에 hide -->\r\n");
      out.write("\t\t<div id=\"login_frame_div\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<div id=\"information_in_image1_wrapper\">\r\n");
      out.write("\t\t\t<h1 id=\"information_in_image1\">지금 바로 원하는 지역의 모임 </h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h1 id=\"information_in_image2\">미플 </h1>\r\n");
      out.write("\t\t\t<h1 id=\"login_count1\" class=\"background_ment\">현재 <a id=\"memberCount\"></a>명의 회원이 미플과 함께하고 있어요.</h1>\r\n");
      out.write("\t\t\t<h1 id=\"login_count2\" class=\"background_ment\"><a id=\"meetingCount\"></a>개의 모임에 지금 바로참여하세요  :)</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/meet.jpg\" id=\"login_image\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 로그인 포지션-->\r\n");
      out.write("\t\t\t<form id=\"login_form\"\r\n");
      out.write("\t\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/member/login\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"login_closeBtn\" value=\"X\" style=\"float:right;\"/>\r\n");
      out.write("\t\t\t\t\t<h1 style=\"clear:both;\">로그인</h1>\r\n");
      out.write("\t\t\t\t\t<br> \r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"id_input\" id=\"id_input\" placeholder=\"아이디를 입력해주세요.\"");
      out.print(saveId != null ? "value='" + saveId + "'" : "");
      out.write("> <br>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"password_input\" id=\"password_input\" placeholder=\"비밀번호를 입력해주세요.\"> <br> \r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"login_submit\" id=\"login_submit\" value=\"로그인\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div id=\"checkbox_findbox_wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"checkbox_wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"saveid\" id=\"saveid\" ");
      out.print(saveId != null ? "checked" : "");
      out.write(" /> \r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"saveid\" id=\"saveidlabel\">로그인 유지하기</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/find\"><span id=\"find_span\">아이디+비밀번호 찾기</span></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t\t<div class=\"enroll_div\" id=\"enroll_div\"  onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/enroll';\" style=\"clear:both\";>\r\n");
      out.write("\t\t\t\t\t\t미플 회원가입하기\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<ol>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList\" id=\"header_li1\">전체</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C1\" id=\"header_li2\">음악</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C2\" id=\"header_li3\">게임</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C3\" id=\"header_li4\">운동</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C4\" id=\"header_li5\">요리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C5\" id=\"header_li6\">독서</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C6\" id=\"header_li7\">재테크</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?category=C7\" id=\"header_li8\">자동차</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/board/boardList\" id=\"header_li9\">자유게시판</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/board/adminBoardList\" id=\"header_li10\">공지사항</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
if(loginMember!=null && loginMember.getMemberRole().equals(MemberService.ADMIN_ROLE)) { 
      out.write("\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\" id=\"header_li11\">관리</a></li>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t");
if(msg!=null){
      out.write("\r\n");
      out.write("\t\t\t\talert(\"");
      out.print(msg);
      out.write("\");\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t");
if(loginMember==null){
      out.write("\r\n");
      out.write("\t\t\t\t$(signup_button).click(function(){\r\n");
      out.write("\t\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/member/enroll\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t$(login_button).click(function() {\r\n");
      out.write("\t\t\t\tvar top = screen.availHeight / 2 - 250;\r\n");
      out.write("\t\t\t\t$(\"#login_frame_div\").attr('style', 'display:flex; top:'+top+'px;');\r\n");
      out.write("\t\t\t\t$(\"#login_frame_wrapper\").attr('style', 'display:flex; top:'+top+'px;');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(id_input.value.length==0){\r\n");
      out.write("\t\t\t\t\t$('#id_input').focus();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$('#password_input').focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(login_closeBtn).click(function(){\r\n");
      out.write("\t\t\t\t$(\"#login_frame_div\").attr('style', 'display:none;');\r\n");
      out.write("\t\t\t\t$(\"#login_frame_wrapper\").attr('style', 'display:none;');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(login_frame_wrapper).click(function(){\r\n");
      out.write("\t\t\t\t$(\"#login_frame_div\").attr('style', 'display:none;');\r\n");
      out.write("\t\t\t\t$(\"#login_frame_wrapper\").attr('style', 'display:none;');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t//총인원과 총모임 ajax\r\n");
      out.write("\t\t\t\t");
if(loginMember==null){
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.print( request.getContextPath());
      out.write("/member/count\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t/* 총인원수 저장 */\r\n");
      out.write("\t\t\t\t\t\tvar memberCount=data;\r\n");
      out.write("\t\t\t\t\t\t$(\"#memberCount\").html(memberCount);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror:function(xhr, status, error){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(xhr, status, error);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.print( request.getContextPath());
      out.write("/member/count\",\r\n");
      out.write("\t\t\t\t\tmethod: \"POST\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tvar meetingCount=data;\r\n");
      out.write("\t\t\t\t\t\t$(\"#meetingCount\").html(meetingCount);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror:function(xhr, status, error){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(xhr, status, error);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//검색창 엔터\r\n");
      out.write("\t\t\tfunction enterkey() {\r\n");
      out.write("\t\t        if (window.event.keyCode == 13) {\r\n");
      out.write("\t\t        \tsearch();\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction search(){\r\n");
      out.write("\t\t\t\tvar $keyword = $(\"#searchKeyword\").val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(/^.{1,}$/.test($keyword)==false){\r\n");
      out.write("\t\t\t\t\t$(\"#searchKeyword\").focus();\r\n");
      out.write("\t\t\t\t\talert(\"검색 키워드를 1글자 이상 입력해주세요\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/meeting/meetingList?search=\"+$keyword;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<section>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/enroll.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Section 1 -->\r\n");
      out.write("<form id=\"ho_enroll_from\"\r\n");
      out.write("\taction=\"");
      out.print(request.getContextPath());
      out.write("/member/enroll\" method=\"POST\">\r\n");
      out.write("\t<div class=\"ho_enroll_box_div\" id=\"ho_enroll_box_div\">\r\n");
      out.write("\t\t<h1>딱 이것만 작성하면 가입완료!</h1>\r\n");
      out.write("\t\t<div class=\"ho_id_form\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"for_enroll_css_wrapper\">\r\n");
      out.write("\t\t\t<h3>아이디</h3>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"input\" name=\"ho_id_input\" id=\"ho_id_input\" placeholder=\"사용하실 아이디를 입력해주세요.\" value=\"\" required> \r\n");
      out.write("\t\t\t<!-- text박스의 id입력한거랑 idTest값이 같으면 중복검사 성공 -->\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"idTest\" value=\"0\" />\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"ho_id_check_button\" id=\"ho_id_check_button\" value=\"중복검사\" required/> <br>\r\n");
      out.write("\t\t\t<div class=\"testwrapper\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"ho_password_form\">\r\n");
      out.write("\t\t\t\t<h3>비밀번호</h3>\r\n");
      out.write("\t\t\t\t<input type=\"password\" class=\"input\" name=\"ho_password_input1\"\r\n");
      out.write("\t\t\t\t\tid=\"ho_password_input1\" placeholder=\"비밀번호를 입력해주세요.(8자 이상)\" required><br>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" id=\"pwd_chk1\"></label>\r\n");
      out.write("\t\t\t\t <input type=\"password\" class=\"input\" name=\"ho_password_input2\"\r\n");
      out.write("\t\t\t\t\tid=\"ho_password_input2\" placeholder=\"비밀번호를 한번 더 입력해주세요.\" required> <br>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" id=\"pwd_chk2\"></label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"ho_name_form\">\r\n");
      out.write("\t\t\t\t<h3>이름</h3>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input\" name=\"ho_name_input\" id=\"ho_name_input\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"이름을 입력해 주세요.\" required> <br>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" id=\"name_chk\"></label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"email_form\">\r\n");
      out.write("\t\t\t\t<h3>이메일</h3>\r\n");
      out.write("\t\t\t\t<input type=\"email\" class=\"input\" name=\"ho_eamil_input\" id=\"ho_eamil_input\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"이메일을 입력해주세요.\" required> \r\n");
      out.write("\t\t\t\t\t<input type=\"button\" name=\"ho_email_check_button\" id=\"ho_email_check_button\" value=\"인증하기\"/>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"ho_eamil_confirm_input\" id=\"ho_eamil_confirm_input\" placeholder=\"인증번호를 입력해주세요.\" style=\"visibility: hidden;\" >\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" name=\"ho_eamil_confirm_button\" id=\"ho_eamil_confirm_button\" value=\"인증번호확인\" style=\"visibility: hidden;\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"emailTest\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"ho_phone_form\">\r\n");
      out.write("\t\t\t\t<h3>휴대폰번호</h3>\r\n");
      out.write("\t\t\t\t<input type=\"number\" class=\"input\" name=\"ho_phone_input\" id=\"ho_phone_input\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"휴대폰 번호 '-'표 없이 입력해 주세요.\" required> <br>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" id=\"phone_chk\"></label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"ho_agremment_form\">\r\n");
      out.write("\t\t\t<h3>약관동의</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"ho_agreement_div\" id=\"ho_agreement_div\">\r\n");
      out.write("\t\t\t<fieldset class=\"ho_agreement_filedset\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"ho_agreement_input1\"\r\n");
      out.write("\t\t\t\t\tid=\"ho_agreement_input1\" onclick=\"chkAll()\"/> <label for=\"ho_agreement_input1\">모두\r\n");
      out.write("\t\t\t\t\t동의합니다.</label> <br>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" class =\"checkbox_ho\" name=\"ho_agreement_input2\"\r\n");
      out.write("\t\t\t\t\tid=\"ho_agreement_input2\" onclick=\"chkOne()\" required />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t <label\r\n");
      out.write("\t\t\t\t\tfor=\"ho_agreement_input2\">만 14세 이상입니다.</label> <label\r\n");
      out.write("\t\t\t\t\tfor=\"ho_agreement_input2\" class=\"ho_necessary\">(필수)</label> <br>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" class =\"checkbox_ho\" name=\"ho_agreement_input3\"\r\n");
      out.write("\t\t\t\t\tid=\"ho_agreement_input3\"  onclick=\"chkOne()\" required /> <label\r\n");
      out.write("\t\t\t\t\tfor=\"ho_agreement_input3\"><u>서비스 이용약관</u>에 동의합니다.</label> <label\r\n");
      out.write("\t\t\t\t\tfor=\"ho_agreement_input3\" class=\"ho_necessary\">(필수)</label> <br>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" class =\"checkbox_ho\" name=\"ho_agreement_input4\"\r\n");
      out.write("\t\t\t\t\tid=\"ho_agreement_input4\"  onclick=\"chkOne()\" required /> <label\r\n");
      out.write("\t\t\t\t\tfor=\"ho_agreement_input4\"><u>개인정보 수집•이용</u> 에 동의합니다.</label> <label\r\n");
      out.write("\t\t\t\t\tfor=\"ho_agreement_input4\" class=\"ho_necessary\">(필수)</label> <br>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" class =\"checkbox_ho\" name=\"ho_agreement_input5\"\r\n");
      out.write("\t\t\t\t\tid=\"ho_agreement_input5\"  onclick=\"chkOne()\" value=\"T\"> <label\r\n");
      out.write("\t\t\t\t\tfor=\"ho_agreement_input5\">이벤트 할인 혜택 알림 수신에 동의합니다.</label> <label\r\n");
      out.write("\t\t\t\t\tfor=\"ho_agreement_input5\" class=\"ho_choice\">(선택)</label> <br>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" class =\"checkbox_ho\" name=\"ho_agreement_input6\"\r\n");
      out.write("\t\t\t\t\tid=\"ho_agreement_input6\"  onclick=\"chkOne()\" value=\"T\" /> <label\r\n");
      out.write("\t\t\t\t\tfor=\"ho_agreement_input5\">장기 미접속 시 계정 활성 상태 유지합니다. </label> <label\r\n");
      out.write("\t\t\t\t\tfor=\"ho_agreement_input5\" class=\"ho_choice\">(선택)</label> <br>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t<br> <input type=\"submit\" id=\"enroll_sumit_button\" value=\"버튼을 누르면 회원가입이 완료됩니다.\"id=\"ho_submit_button\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t//아이디중복검사 \r\n");
      out.write("\t$(ho_id_check_button).click(function(){\r\n");
      out.write("\t\tvar id = $('#ho_id_input').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//아이디유효성검사\r\n");
      out.write("\t\tvar $ho_id_input = $(\"#ho_id_input\");\r\n");
      out.write("\t\tif (/^[a-zA-Z0-9_]{4,}$/.test($ho_id_input.val()) == false) {\r\n");
      out.write("\t\t\talert(\"유효한 아이디를 입력해주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//DB를 통해 중복검사\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/member/checkid\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tmemberid : id\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tmethod: \"POST\",\r\n");
      out.write("\t\t\tdataType: \"text\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t$(\".testwrapper\").html(data);\r\n");
      out.write("\t\t\t\tif(data==\"사용가능한 아이디입니다.\"){\r\n");
      out.write("\t\t\t\t\t$(\"[name=idTest]\").val(\"1\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$('#ho_id_input').val(\"\").focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, error){\r\n");
      out.write("\t\t\t\tconsole.log(\"error call!\");\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, error);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//아이디 중복검사 이후 id값 변경시 다시 중복검사 하게끔\r\n");
      out.write("\t$(\"#ho_id_input\").change(function(){\r\n");
      out.write("\t\t$(\"[name=idTest]\").val(\"0\");\r\n");
      out.write("\t\t$(\".testwrapper\").html(\"\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//첫번째 비밀번호 유효성검사\r\n");
      out.write("\t$(\"#ho_password_input1\").change(function(){\r\n");
      out.write("\t\tvar p1 = $(\"#ho_password_input1\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(/^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$/.test(p1.val())==false){\r\n");
      out.write("\t\t\t$(\"#pwd_chk1\").html(\"최소 8 자, 최소 하나의 문자 및 하나의 숫자를 입력해주세요.<br>\");\r\n");
      out.write("\t\t\t$(\"#pwd_chk1\").attr('style', 'visibility:visible;');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else if(/^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$/.test(p1.val())==true) {\r\n");
      out.write("\t\t\t$(\"#pwd_chk1\").html(\"\");\r\n");
      out.write("\t\t\t$(\"#pwd_chk1\").attr('style', 'visibility:hidden;');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//두번째 비밀번호 유효성검사\r\n");
      out.write("\t$(\"#ho_password_input2\").change(function(){\r\n");
      out.write("\t\tvar p1 = $(\"#ho_password_input1\");\r\n");
      out.write("\t\tvar p2 = $(\"#ho_password_input2\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(p1.val() != p2.val()){\r\n");
      out.write("\t\t\t$(\"#pwd_chk2\").html(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t$(\"#pwd_chk2\").attr('style', 'visibility:visible;');\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#pwd_chk2\").html(\"\");\r\n");
      out.write("\t\t\t$(\"#pwd_chk2\").attr('style', 'visibility:hidden;');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//이름 유효성검사\r\n");
      out.write("\t$(\"#ho_name_input\").change(function(){\r\n");
      out.write("\tvar $ho_name_input = $(\"#ho_name_input\");\r\n");
      out.write("\t\r\n");
      out.write("\tif(/^[가-힣]{2,}$/.test($ho_name_input.val()) == false){\r\n");
      out.write("\t\t$(\"#name_chk\").html(\"이름은 한글 2글자 이상이어야 합니다.\");\r\n");
      out.write("\t\t$(\"#name_chk\").attr('style', 'visibility:visible;');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(\"#name_chk\").html(\"\");\r\n");
      out.write("\t\t$(\"#name_chk\").attr('style', 'visibility:hidden;');\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//이메일 인증하기 구현 \r\n");
      out.write("\t$(ho_email_check_button).click(function(){\r\n");
      out.write("\t\tvar eamilId = $('#ho_eamil_input').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//미플에서 보낼 인증번호 담는곳\r\n");
      out.write("\t\tvar confirmCode;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/member/send\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tmemberEamilId : eamilId\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tmethod: \"POST\",\r\n");
      out.write("\t\t\tdataType: \"text\",\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//성공했을시\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tif(data==\"Ban\"){\r\n");
      out.write("\t\t\t\t\talert(\"가입이 제한된 이메일 입니다.\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(data==\"overlap\"){\r\n");
      out.write("\t\t\t\t\talert(\"이미 가입된 이메일 입니다.\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tconfirmCode = data;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//인증번호 박스, 버튼나타나기\t\t\t\r\n");
      out.write("\t\t\t$(\"#ho_eamil_confirm_input, #ho_eamil_confirm_button\").attr('style', 'visibility:visible;');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t//인증번호 확인눌렀을 시 구현\r\n");
      out.write("\t\t\t\t$(ho_eamil_confirm_button).click(function(){\r\n");
      out.write("\t\t\t\t\tvar memberConfirmCode = $('#ho_eamil_confirm_input').val();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(confirmCode==memberConfirmCode){\r\n");
      out.write("\t\t\t\t\t\talert(\"인증에 성공하셨습니다\");\r\n");
      out.write("\t\t\t\t\t\t$(\"[name=emailTest]\").val(\"1\"); //인증에 성공하면 value를 1로바꿈\r\n");
      out.write("\t\t\t\t\t\t$('#ho_eamil_input, #ho_eamil_confirm_input').attr('readonly', true); //인증성공하면 이메일 + 인증번호창 readonly\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"인증에 실패하셨습니다\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, error){\r\n");
      out.write("\t\t\t\tconsole.log(\"error call!\");\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, error);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//휴대폰 유효성검사\r\n");
      out.write("\t$(\"#ho_phone_input\").change(function(){\r\n");
      out.write("\t\tvar $ho_phone_input = $(\"#ho_phone_input\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(/^010[0-9]{8}$/.test($ho_phone_input.val()) == false){\r\n");
      out.write("\t\t\t$(\"#phone_chk\").html(\"유효한 전화번호가 아닙니다.\");\r\n");
      out.write("\t\t\t$(\"#phone_chk\").attr('style', 'visibility:visible;');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#phone_chk\").html(\"\");\r\n");
      out.write("\t\t\t$(\"#phone_chk\").attr('style', 'visibility:hidden;');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//모두동의하기 구현\r\n");
      out.write("\tfunction chkAll() {\r\n");
      out.write("        if ($(\"#ho_agreement_input1\").is(':checked')) {\r\n");
      out.write("            $(\"#ho_agreement_input2, #ho_agreement_input3, #ho_agreement_input4, #ho_agreement_input5, #ho_agreement_input6\").prop(\"checked\", true);\r\n");
      out.write("        } else {\r\n");
      out.write("            $(\"#ho_agreement_input2, #ho_agreement_input3, #ho_agreement_input4, #ho_agreement_input5, #ho_agreement_input6\").prop(\"checked\", false);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//하나라도 체크헤제 시 모두동의하기 헤제취소\r\n");
      out.write("\tfunction chkOne() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar checkall = document.querySelector(\"#ho_agreement_input1\");\r\n");
      out.write("\t\tvar checkboxes = document.querySelectorAll(\".checkbox_ho\");\r\n");
      out.write("\t\tvar checkedCheckBox = document.querySelectorAll(\".checkbox_ho:checked\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcheckall.checked = (checkboxes.length == checkedCheckBox.length);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//제출버튼 클릭시 모든 값 유무 확인\r\n");
      out.write("\t$(\"#ho_enroll_from\").submit(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//중복검사 실시 유무\r\n");
      out.write("\t\tif($(\"[name=idTest]\").val() != \"1\"){\r\n");
      out.write("\t\t\talert(\"중복검사를 해주세요\");\r\n");
      out.write("\t\t\t$(\"#ho_id_input\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//비밀번호 유효성 여부결과표시가 나와있으면 return\r\n");
      out.write("\t\tif($(\"#pwd_chk1\").css(\"visibility\") != \"hidden\"){\r\n");
      out.write("\t\t\talert(\"비밀번호를 제대로 입력 해주세요\");\r\n");
      out.write("\t\t\t$(\"#ho_password_input1\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#pwd_chk2\").css(\"visibility\") != \"hidden\"){\r\n");
      out.write("\t\t\talert(\"비밀번호를 제대로 입력 해주세요\");\r\n");
      out.write("\t\t\t$(\"#ho_password_input2\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//이름 유효성 여부표시가 나와있으면 return\r\n");
      out.write("\t\tif($(\"#name_chk\").css(\"visibility\") != \"hidden\"){\r\n");
      out.write("\t\t\talert(\"이름을 제대로 입력 해주세요\");\r\n");
      out.write("\t\t\t$(\"#ho_name_input\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//이메일 인증 실시 유무\r\n");
      out.write("\t\tif($(\"[name=emailTest]\").val() != \"1\"){\r\n");
      out.write("\t\t\talert(\"이메일인증 해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//이메일유효성 hidden이면 인증하기\r\n");
      out.write("\t\tif($(\"#ho_eamil_confirm_button\").css(\"visibility\") == \"hidden\"){\r\n");
      out.write("\t\t\talert(\"이메일 인증을 해주세요\");\r\n");
      out.write("\t\t\t$(\"#ho_eamil_input\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//휴대폰유효성 여부표시가 나와있으면 return\r\n");
      out.write("\t\tif($(\"#phone_chk\").css(\"visibility\") != \"hidden\"){\r\n");
      out.write("\t\t\talert(\"휴대폰번호를 제대로 입력 해주세요\");\r\n");
      out.write("\t\t\t$(\"#ho_phone_input\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/footer.css\" />\r\n");
      out.write("</section>\r\n");
      out.write("<hr style=\"margin-top:40px\" />\r\n");
      out.write("<footer>\r\n");
      out.write("        <div class=\"meeple-footer container\">\r\n");
      out.write("        <div class=\"infofooter\">\r\n");
      out.write("            <h1>MeetPeople 제작 정보</h1>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <p>MeetPeople</p>\r\n");
      out.write("            <p>소속 : KH정보교육원 | 서울특별시 강남구 역삼동 823-25</p>\r\n");
      out.write("            <p>팀장 : 김윤수</p>\r\n");
      out.write("            <p>팀원 : 천호현 강종성 박요한 이승우 최한성</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"etc\">\r\n");
      out.write("            <h1>관련 사이트</h1>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <p>김윤수 : <a href=\"https://github.com/kimdia200\" target=\"_blank\">https://github.com/kimdia200 <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("            <p>강종성 : <a href=\"https://github.com/bellcastle88\" target=\"_blank\">https://github.com/bellcastle88 <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("            <p>박요한 : <a href=\"https://github.com/dygksqkr12\" target=\"_blank\">https://github.com/dygksqkr12 <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("            <p>이승우 : <a href=\"https://github.com/onreverse01\" target=\"_blank\">https://github.com/onreverse01 <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("            <p>천호현 : <a href=\"https://github.com/hohyuncheon\" target=\"_blank\">https://github.com/hohyuncheon <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("            <p>최한성 : <a href=\"https://github.com/HSdover\" target=\"_blank\">https://github.com/HSdover <i class=\"fas fa-external-link-alt\"></i></a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"contact\">\r\n");
      out.write("            <h1>고객센터</h1>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/claim/claimMenu\">문의하기 <i class=\"fas fa-external-link-alt\"></i></a>\r\n");
      out.write("            <p>Tel : 010-6353-4583 (평일 09:00 ~ 18:00)</p>\r\n");
      out.write("            <p>Mail : meetpeople_kh@gmail.com</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script \r\n");
      out.write("     src=\"https://kit.fontawesome.com/39a2f80180.js\"\r\n");
      out.write("     crossorigin=\"anonymous\"\r\n");
      out.write("     ></script>\r\n");
      out.write("</footer>\r\n");
      out.write("        <hr style=\"margin-top:40px; width:100%;\">\r\n");
      out.write("        <h2 id=\"last\">Copyright 2021. &lt; KH-SEMI-PROJECT &gt; all rights reserved.</h2>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
